# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sr < Formula
  desc "Bulk reverse DNS (PTR) lookups on CIDR ranges"
  homepage "https://github.com/klp2/sr"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/klp2/sr/releases/download/v0.5.0/sr_0.5.0_darwin_amd64.tar.gz"
      sha256 "dfbb5502ecb4e7af134888237bb26d1d89cce6188e50d5260c65bee1896be10f"

      def install
        bin.install "sr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/klp2/sr/releases/download/v0.5.0/sr_0.5.0_darwin_arm64.tar.gz"
      sha256 "0570a293ebca492d01a3d8bb892b7772b5a7915c6c861734d6c2236616161a00"

      def install
        bin.install "sr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/klp2/sr/releases/download/v0.5.0/sr_0.5.0_linux_amd64.tar.gz"
      sha256 "78481ad27690bac0ef231c817dcca91cc5f0ed99f0ff6682d55153de09cd7ddb"
      def install
        bin.install "sr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klp2/sr/releases/download/v0.5.0/sr_0.5.0_linux_arm64.tar.gz"
      sha256 "a46c78889b37a3befb9c00b10b1d1af54ac255a65314db2234b5333ae1a5caa2"
      def install
        bin.install "sr"
      end
    end
  end

  test do
    assert_match "sr (ShowReverse)", shell_output("#{bin}/sr --help")
  end
end
