# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sr < Formula
  desc "Bulk reverse DNS (PTR) lookups on CIDR ranges"
  homepage "https://github.com/klp2/sr"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/klp2/sr/releases/download/v0.3.0/sr_0.3.0_darwin_amd64.tar.gz"
      sha256 "371556ba69325c04c260ca83018c91b688cc798f37d8608a034ad2d2024df885"

      def install
        bin.install "sr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/klp2/sr/releases/download/v0.3.0/sr_0.3.0_darwin_arm64.tar.gz"
      sha256 "f819f51dc1465b3f720f41714c0e81e73caf1a454930cd0398d8c8e27e71d6c2"

      def install
        bin.install "sr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/klp2/sr/releases/download/v0.3.0/sr_0.3.0_linux_amd64.tar.gz"
      sha256 "6b057e304de5e18b5908482bfa3eac26c5436e8c6fe474cd9599b2e1d9ad7b39"
      def install
        bin.install "sr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klp2/sr/releases/download/v0.3.0/sr_0.3.0_linux_arm64.tar.gz"
      sha256 "820e033d6dc4eb84be3a089bf4c6a80dd86315df90b1405afea095aea2601efd"
      def install
        bin.install "sr"
      end
    end
  end

  test do
    assert_match "sr (ShowReverse)", shell_output("#{bin}/sr --help")
  end
end
